// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace WiDocApi_test.Models;

public partial class Person
{
    [Key]
    [WiDocApiSchema("Person ID for this person")]
    public int PersonID { get; set; }

    [StringLength(50)]
    [WiDocApiSchema("First name of the person")]
    public string FirstName { get; set; }

    [StringLength(50)]
    [WiDocApiSchema("Last name of the person")]
    public string LastName { get; set; }

    [WiDocApiSchema("Age of the person, nullable")]
    public int? Age { get; set; }

    [StringLength(10)]
    [WiDocApiSchema("Gender of the person, typically 'M' or 'F'")]
    public string Gender { get; set; }

    [StringLength(100)]
    [WiDocApiSchema("Email address of the person")]
    public string Email { get; set; }

    [StringLength(50)]
    [WiDocApiSchema("State where the person resides")]
    public string State { get; set; }

    [StringLength(10)]
    [WiDocApiSchema("Zip code of the person's address")]
    public string ZipCode { get; set; }
}