// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace WiDocApi_test.Models;

public partial class Person
{
    [Key]
    [WiDocApiSchema("Person ID for this person")]
    public int PersonID { get; set; }

    [StringLength(50)]
    [WiDocApiSchema("First name of the person")]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Required]
    [WiDocApiSchema("Last name of the person")]
    public string LastName { get; set; }

    [WiDocApiSchema("Age of the person, nullable")]
    public int? Age { get; set; }

    [StringLength(10)]
    [WiDocApiSchema("Gender of the person, typically 'M' or 'F'")]
    public string Gender { get; set; }

    [StringLength(100)]
    [WiDocApiSchema("Email address of the person")]
    public string Email { get; set; }

    [StringLength(50)]
    [WiDocApiSchema("State where the person resides")]
    public string State { get; set; }

    [StringLength(10)]
    [WiDocApiSchema("Zip code of the person's address")]
    public string ZipCode { get; set; }
}
public record LogMessages
{
    /// <summary>
    /// Gets or sets the line number of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the line number of the log message")]
    public int LineNumber { get; set; }

    /// <summary>
    /// Gets or sets the source name of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the source name of the log message")]
    public string? SourceName { get; set; }

    /// <summary>
    /// Gets or sets the level of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the level of the log message")]
    public string? Level { get; set; }

    /// <summary>
    /// Gets or sets the code of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the code of the log message")]
    public string? Code { get; set; }

    /// <summary>
    /// Gets or sets the create date of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the create date of the log message")]
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// Gets or sets the messages of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the messages of the log message")]
    public string? Messages { get; set; }

    /// <summary>
    /// Gets or sets the exception of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the exception of the log message")]
    public string? Exception { get; set; }

    /// <summary>
    /// Gets or sets the properties of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the properties of the log message")]
    public string? Properties { get; set; }

    /// <summary>
    /// Gets or sets the note of the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets the note of the log message")]
    public string? Note { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether to send mail for the log message.
    /// </summary>
    [WiDocApiSchema("Gets or sets a value indicating whether to send mail for the log message")]
    public string? sendmail { get; set; } = "false";
}