// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WiDocApi_test.Models;

public partial class SamplePersonsContext : DbContext
{
   
    public SamplePersonsContext(DbContextOptions<SamplePersonsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> Persons { get; set; }

    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.PersonID).HasName("PK__Persons__AA2FFB8566BE15F9");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}